server:
  port: 8080

database:
  dbname: 
  dbuser: "dbuser"
  dbpassword: "dbpassword"

discord:
  prefix: "~~"
  token: ""

EXAMPLE_VAR: "variable from config.yml"
EXAMPLE_PATH: "path from config.yml"